<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="163911" started-at="2021-05-29T17:04:11Z" finished-at="2021-05-29T17:06:55Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="163911" started-at="2021-05-29T17:04:11Z" finished-at="2021-05-29T17:06:55Z">
      <class name="com.qa.myntra.testcases.BagPageTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.qa.myntra.testcases.BagPageTest@5b275dab]" name="setup" is-config="true" duration-ms="153031" started-at="2021-05-29T22:34:11Z" finished-at="2021-05-29T22:36:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="bagpage()[pri:0, instance:com.qa.myntra.testcases.BagPageTest@5b275dab]" name="bagpage" duration-ms="10532" started-at="2021-05-29T22:36:44Z" finished-at="2021-05-29T22:36:55Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [itemContainer-base-brand] but found [itemdetails-itemDetailsLabel]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [itemContainer-base-brand] but found [itemdetails-itemDetailsLabel]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.qa.myntra.testcases.BagPageTest.bagpage(BagPageTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bagpage -->
      </class> <!-- com.qa.myntra.testcases.BagPageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
